# Installing NumPy

In [1]:
! pip install numpy

In [2]:
! conda install numpy

/bin/bash: conda: command not found


# Import and version check 

In [3]:
import numpy as np

print(np.__version__)

1.18.5


# Python List to NumPy array

In [4]:
lst = [1, 7, 0, 6, 2, 5, 6] 
  
# converting list to array 
arr = np.array(lst) 

print(type(lst), "-->", lst)
print(type(arr), "-->", arr)

<class 'list'> --> [1, 7, 0, 6, 2, 5, 6]
<class 'numpy.ndarray'> --> [1 7 0 6 2 5 6]


# Python tupule to NumPy ndarray

In [5]:
tup = (1, 7, 0, 6) 
  
# converting tupule to array 
arr = np.array(tup) 

print(type(tup), "-->", tup)
print(type(arr), "-->", arr)

<class 'tuple'> --> (1, 7, 0, 6)
<class 'numpy.ndarray'> --> [1 7 0 6]


# 1d ndarray 

In [6]:
arr = np.array([1, 2, 3])
print(type(arr))
print("ndim: ", arr.ndim)
print(arr)

<class 'numpy.ndarray'>
ndim:  1
[1 2 3]


# 2d array using NumPy

In [7]:
arr2d = np.array([
                  (1, 2, 3),
                  (4, 5, 6)
                ])
print(type(arr2d))
print("ndim: ", arr2d.ndim)
print("size: ", arr2d.size)
print("itemsize: ", arr2d.itemsize)
print("dtype: ", arr2d.dtype)
print("shape: ", arr2d.shape)
print(arr2d)

<class 'numpy.ndarray'>
ndim:  2
size:  6
itemsize:  8
dtype:  int64
shape:  (2, 3)
[[1 2 3]
 [4 5 6]]


In [19]:
arr2d = np.array([
                  (1, 2, 3),
                  (4, 5)
                ])
print(type(arr2d))
print("ndim: ", arr2d.ndim)
print("size: ", arr2d.size)
print("itemsize: ", arr2d.itemsize)
print("dtype: ", arr2d.dtype)
print("shape: ", arr2d.shape)
print(arr2d)

<class 'numpy.ndarray'>
ndim:  1
size:  2
itemsize:  8
dtype:  object
shape:  (2,)
[(1, 2, 3) (4, 5)]


# 3d array using NumPy

In [20]:
arr3d = np.array([
                  [
                    [1, 2, 3, 4],
                    [1, 2, 3, 4]
                  ],
                  [
                   [4, 5, 6, 7],
                   [4, 5, 6, 7]
                  ], 
                  [
                   [7, 8, 9, 8],
                   [7, 8, 9, 8]
                  ]
                ])
print(type(arr3d))
print("ndim: ", arr3d.ndim)
print("size: ", arr3d.size)
print("shape: ", arr3d.shape)
print("itemsize", arr3d.itemsize)
print("\n")
print(arr3d)

<class 'numpy.ndarray'>
ndim:  3
size:  24
shape:  (3, 2, 4)
itemsize 8


[[[1 2 3 4]
  [1 2 3 4]]

 [[4 5 6 7]
  [4 5 6 7]]

 [[7 8 9 8]
  [7 8 9 8]]]


# 5d ndarray in NumPy

In [21]:
arr5d = np.array([
                  [
                   [
                    [
                     (1, 2, 3)
                    ]
                   ]
                  ], 
                  
                  [
                   [
                    [
                     (4, 5, 6)
                    ]
                   ]
                  ], 
                  [
                   [
                    [
                     (7, 8, 9)
                     ]
                   ]
                  ], 
                  [
                   [
                    [
                     (10, 11, 12)
                    ]
                   ]
                  ], 
                  [
                   [
                    [
                     (13, 14, 15)
                    ]
                   ]
                  ]
                ])
print(type(arr5d))
print("ndim: ", arr5d.ndim)
print("shape: ", arr5d.shape)
print("dtype: ", arr5d.dtype)
print(arr5d)

<class 'numpy.ndarray'>
ndim:  5
shape:  (5, 1, 1, 1, 3)
dtype:  int64
[[[[[ 1  2  3]]]]



 [[[[ 4  5  6]]]]



 [[[[ 7  8  9]]]]



 [[[[10 11 12]]]]



 [[[[13 14 15]]]]]


# Performance of NumPy  

In [22]:
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
result = []
start=time.time()
for i in range(len(L1)) :
  result.append(L1[i] + L2[i])
print((time.time()-start)*1000)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start=time.time()
result= A1+A2
print((time.time()-start)*1000)

467.5612449645996
302.8230667114258
48.72775077819824
